apiVersion: v1
kind: Service
metadata:
  name: jwtdb-dev
spec:
  ports:
  - port: 5432
---
apiVersion: v1
kind: Endpoints
metadata:
  name: jwtdb-dev
subsets:
  - addresses:
    - ip: 10.100.X.XXX  #local dev testing ip
    ports:
    - port: 5432
