//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.4.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace JwtSecurity.DatabaseSpecific
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	internal static class PersistenceInfoProviderSingleton
	{
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton() {	}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance() { return _providerInstance; }
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitApiClientEntityMappings();
			InitRoleEntityMappings();
			InitUserEntityMappings();
			InitUserRoleEntityMappings();
		}

		/// <summary>Inits ApiClientEntity's mappings</summary>
		private void InitApiClientEntityMappings()
		{
			this.AddElementMapping("ApiClientEntity", @"JwtSecurity", @"public", "ApiClient", 5, 0);
			this.AddElementFieldMapping("ApiClientEntity", "ClientId", "ClientId", false, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("ApiClientEntity", "ClientName", "ClientName", false, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("ApiClientEntity", "ClientSecret", "ClientSecret", false, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("ApiClientEntity", "RefreshTokenLifetimeMinutes", "RefreshTokenLifetimeMinutes", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 3);
			this.AddElementFieldMapping("ApiClientEntity", "TokenLifetimeMinutes", "TokenLifetimeMinutes", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 4);
		}

		/// <summary>Inits RoleEntity's mappings</summary>
		private void InitRoleEntityMappings()
		{
			this.AddElementMapping("RoleEntity", @"JwtSecurity", @"public", "Role", 2, 0);
			this.AddElementFieldMapping("RoleEntity", "RoleId", "RoleId", false, "Integer", 0, 10, 0, true, "public.Role_RoleId_seq", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("RoleEntity", "RoleName", "RoleName", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 1);
		}

		/// <summary>Inits UserEntity's mappings</summary>
		private void InitUserEntityMappings()
		{
			this.AddElementMapping("UserEntity", @"JwtSecurity", @"public", "User", 4, 0);
			this.AddElementFieldMapping("UserEntity", "PasswordHash", "PasswordHash", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("UserEntity", "Salt", "Salt", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("UserEntity", "UserEmail", "UserEmail", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("UserEntity", "UserId", "UserId", false, "Integer", 0, 10, 0, true, "public.User_UserId_seq", null, typeof(System.Int32), 3);
		}

		/// <summary>Inits UserRoleEntity's mappings</summary>
		private void InitUserRoleEntityMappings()
		{
			this.AddElementMapping("UserRoleEntity", @"JwtSecurity", @"public", "UserRole", 3, 0);
			this.AddElementFieldMapping("UserRoleEntity", "RoleId", "RoleId", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("UserRoleEntity", "UserId", "UserId", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 1);
			this.AddElementFieldMapping("UserRoleEntity", "UserRoleId", "UserRoleId", false, "Integer", 0, 10, 0, true, "public.UserRole_UserRoleId_seq", null, typeof(System.Int32), 2);
		}

	}
}
