//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.4.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace JwtSecurityContracts.Persistence
{
	/// <summary>Static class for (extension) methods for fetching and projecting instances of JwtSecurityContracts.DtoClasses.ApiClientDto from the entity model.</summary>
	public static partial class ApiClientDtoPersistence
	{
		private static readonly System.Linq.Expressions.Expression<Func<JwtSecurity.EntityClasses.ApiClientEntity, JwtSecurityContracts.DtoClasses.ApiClientDto>> _projectorExpression = CreateProjectionFunc();
		private static readonly Func<JwtSecurity.EntityClasses.ApiClientEntity, JwtSecurityContracts.DtoClasses.ApiClientDto> _compiledProjector = CreateProjectionFunc().Compile();
	
		/// <summary>Empty static ctor for triggering initialization of static members in a thread-safe manner</summary>
		static ApiClientDtoPersistence() { }
	
		/// <summary>Extension method which produces a projection to JwtSecurityContracts.DtoClasses.ApiClientDto which instances are projected from the 
		/// results of the specified baseQuery, which returns JwtSecurity.EntityClasses.ApiClientEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <returns>IQueryable to retrieve JwtSecurityContracts.DtoClasses.ApiClientDto instances</returns>
		public static IQueryable<JwtSecurityContracts.DtoClasses.ApiClientDto> ProjectToApiClientDto(this IQueryable<JwtSecurity.EntityClasses.ApiClientEntity> baseQuery)
		{
			return baseQuery.Select(_projectorExpression);
		}
		
		/// <summary>Extension method which produces a projection to JwtSecurityContracts.DtoClasses.ApiClientDto which instances are projected from the
		/// JwtSecurity.EntityClasses.ApiClientEntity entity instance specified, the root entity of the derived element returned by this method.</summary>
		/// <param name="entity">The entity to project from.</param>
		/// <returns>JwtSecurity.EntityClasses.ApiClientEntity instance created from the specified entity instance</returns>
		public static JwtSecurityContracts.DtoClasses.ApiClientDto ProjectToApiClientDto(this JwtSecurity.EntityClasses.ApiClientEntity entity)
		{
			return _compiledProjector(entity);
		}
		
		private static System.Linq.Expressions.Expression<Func<JwtSecurity.EntityClasses.ApiClientEntity, JwtSecurityContracts.DtoClasses.ApiClientDto>> CreateProjectionFunc()
		{
			return p__0 => new JwtSecurityContracts.DtoClasses.ApiClientDto()
			{
				ClientId = p__0.ClientId,
				ClientName = p__0.ClientName,
				ClientSecret = p__0.ClientSecret,
				RefreshTokenLifetimeMinutes = p__0.RefreshTokenLifetimeMinutes,
				TokenLifetimeMinutes = p__0.TokenLifetimeMinutes,
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegion_ApiClientDto 
	// __LLBLGENPRO_USER_CODE_REGION_END 
			};
		}
	}
}

