//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.4.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace JwtSecurityContracts.Persistence
{
	/// <summary>Static class for (extension) methods for fetching and projecting instances of JwtSecurityContracts.DtoClasses.RoleDto from the entity model.</summary>
	public static partial class RoleDtoPersistence
	{
		private static readonly System.Linq.Expressions.Expression<Func<JwtSecurity.EntityClasses.RoleEntity, JwtSecurityContracts.DtoClasses.RoleDto>> _projectorExpression = CreateProjectionFunc();
		private static readonly Func<JwtSecurity.EntityClasses.RoleEntity, JwtSecurityContracts.DtoClasses.RoleDto> _compiledProjector = CreateProjectionFunc().Compile();
	
		/// <summary>Empty static ctor for triggering initialization of static members in a thread-safe manner</summary>
		static RoleDtoPersistence() { }
	
		/// <summary>Extension method which produces a projection to JwtSecurityContracts.DtoClasses.RoleDto which instances are projected from the 
		/// results of the specified baseQuery, which returns JwtSecurity.EntityClasses.RoleEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <returns>IQueryable to retrieve JwtSecurityContracts.DtoClasses.RoleDto instances</returns>
		public static IQueryable<JwtSecurityContracts.DtoClasses.RoleDto> ProjectToRoleDto(this IQueryable<JwtSecurity.EntityClasses.RoleEntity> baseQuery)
		{
			return baseQuery.Select(_projectorExpression);
		}
		
		/// <summary>Extension method which produces a projection to JwtSecurityContracts.DtoClasses.RoleDto which instances are projected from the
		/// JwtSecurity.EntityClasses.RoleEntity entity instance specified, the root entity of the derived element returned by this method.</summary>
		/// <param name="entity">The entity to project from.</param>
		/// <returns>JwtSecurity.EntityClasses.RoleEntity instance created from the specified entity instance</returns>
		public static JwtSecurityContracts.DtoClasses.RoleDto ProjectToRoleDto(this JwtSecurity.EntityClasses.RoleEntity entity)
		{
			return _compiledProjector(entity);
		}
		
		private static System.Linq.Expressions.Expression<Func<JwtSecurity.EntityClasses.RoleEntity, JwtSecurityContracts.DtoClasses.RoleDto>> CreateProjectionFunc()
		{
			return p__0 => new JwtSecurityContracts.DtoClasses.RoleDto()
			{
				RoleId = p__0.RoleId,
				RoleName = p__0.RoleName,
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegion_RoleDto 
	// __LLBLGENPRO_USER_CODE_REGION_END 
			};
		}
	}
}

