//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.4.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace JwtSecurityContracts.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Role'.</summary>
	[Serializable]
	[DataContract]
	public partial class RoleDto
	{
		/// <summary>Gets or sets the RoleId field. Derived from Entity Model Field 'Role.RoleId'</summary>
		[DataMember]
		public System.Int32 RoleId { get; set; }
		/// <summary>Gets or sets the RoleName field. Derived from Entity Model Field 'Role.RoleName'</summary>
		[DataMember]
		public System.String RoleName { get; set; }
	}

}




