//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.4.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace JwtSecurityContracts.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'User'.</summary>
	[Serializable]
	[DataContract]
	public partial class UserDto
	{
		/// <summary>Gets or sets the PasswordHash field. Derived from Entity Model Field 'User.PasswordHash'</summary>
		[DataMember]
		public System.String PasswordHash { get; set; }
		/// <summary>Gets or sets the Salt field. Derived from Entity Model Field 'User.Salt'</summary>
		[DataMember]
		public System.String Salt { get; set; }
		/// <summary>Gets or sets the UserEmail field. Derived from Entity Model Field 'User.UserEmail'</summary>
		[DataMember]
		public System.String UserEmail { get; set; }
		/// <summary>Gets or sets the UserId field. Derived from Entity Model Field 'User.UserId'</summary>
		[DataMember]
		public System.Int32 UserId { get; set; }
		/// <summary>Gets or sets the UserRoles field. </summary>
		[DataMember]
		public List<UserDtoTypes.UserRole> UserRoles { get; set; }
	}

	namespace UserDtoTypes
	{
		/// <summary> DTO class which is derived from the entity 'UserRole (UserRoles)'.</summary>
		[Serializable]
		[DataContract]
		public partial class UserRole
		{
			/// <summary>Gets or sets the Role field. </summary>
			[DataMember]
			public UserRoleTypes.Role Role { get; set; }
		}

		namespace UserRoleTypes
		{
			/// <summary> DTO class which is derived from the entity 'Role (UserRoles.Role)'.</summary>
			[Serializable]
			[DataContract]
			public partial class Role
			{
				/// <summary>Gets or sets the RoleId field. Derived from Entity Model Field 'Role.RoleId'</summary>
				[DataMember]
				public System.Int32 RoleId { get; set; }
				/// <summary>Gets or sets the RoleName field. Derived from Entity Model Field 'Role.RoleName'</summary>
				[DataMember]
				public System.String RoleName { get; set; }
			}
		}
	}

}




