//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.4.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using JwtSecurity.HelperClasses;
using JwtSecurity.FactoryClasses;
using JwtSecurity.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace JwtSecurity.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'ApiClient'.<br/><br/></summary>
	[Serializable]
	public partial class ApiClientEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static ApiClientEntityStaticMetaData _staticMetaData = new ApiClientEntityStaticMetaData();
		private static ApiClientRelations _relationsFactory = new ApiClientRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ApiClientEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ApiClientEntityStaticMetaData()
			{
				SetEntityCoreInfo("ApiClientEntity", InheritanceHierarchyType.None, false, (int)JwtSecurity.EntityType.ApiClientEntity, typeof(ApiClientEntity), typeof(ApiClientEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static ApiClientEntity()
		{
		}

		/// <summary> CTor</summary>
		public ApiClientEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ApiClientEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ApiClientEntity</param>
		public ApiClientEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="clientId">PK value for ApiClient which data should be fetched into this ApiClient object</param>
		public ApiClientEntity(System.String clientId) : this(clientId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="clientId">PK value for ApiClient which data should be fetched into this ApiClient object</param>
		/// <param name="validator">The custom validator object for this ApiClientEntity</param>
		public ApiClientEntity(System.String clientId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.ClientId = clientId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ApiClientEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ApiClientEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ApiClientRelations Relations { get { return _relationsFactory; } }

		/// <summary>The ClientId property of the Entity ApiClient<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ApiClient"."ClientId".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.String ClientId
		{
			get { return (System.String)GetValue((int)ApiClientFieldIndex.ClientId, true); }
			set	{ SetValue((int)ApiClientFieldIndex.ClientId, value); }
		}

		/// <summary>The ClientName property of the Entity ApiClient<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ApiClient"."ClientName".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String ClientName
		{
			get { return (System.String)GetValue((int)ApiClientFieldIndex.ClientName, true); }
			set	{ SetValue((int)ApiClientFieldIndex.ClientName, value); }
		}

		/// <summary>The ClientSecret property of the Entity ApiClient<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ApiClient"."ClientSecret".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String ClientSecret
		{
			get { return (System.String)GetValue((int)ApiClientFieldIndex.ClientSecret, true); }
			set	{ SetValue((int)ApiClientFieldIndex.ClientSecret, value); }
		}

		/// <summary>The RefreshTokenLifetimeMinutes property of the Entity ApiClient<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ApiClient"."RefreshTokenLifetimeMinutes".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 RefreshTokenLifetimeMinutes
		{
			get { return (System.Int32)GetValue((int)ApiClientFieldIndex.RefreshTokenLifetimeMinutes, true); }
			set	{ SetValue((int)ApiClientFieldIndex.RefreshTokenLifetimeMinutes, value); }
		}

		/// <summary>The TokenLifetimeMinutes property of the Entity ApiClient<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ApiClient"."TokenLifetimeMinutes".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 TokenLifetimeMinutes
		{
			get { return (System.Int32)GetValue((int)ApiClientFieldIndex.TokenLifetimeMinutes, true); }
			set	{ SetValue((int)ApiClientFieldIndex.TokenLifetimeMinutes, value); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END
	}
}

namespace JwtSecurity
{
	public enum ApiClientFieldIndex
	{
		///<summary>ClientId. </summary>
		ClientId,
		///<summary>ClientName. </summary>
		ClientName,
		///<summary>ClientSecret. </summary>
		ClientSecret,
		///<summary>RefreshTokenLifetimeMinutes. </summary>
		RefreshTokenLifetimeMinutes,
		///<summary>TokenLifetimeMinutes. </summary>
		TokenLifetimeMinutes,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace JwtSecurity.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: ApiClient. </summary>
	public partial class ApiClientRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticApiClientRelations
	{

		/// <summary>CTor</summary>
		static StaticApiClientRelations() { }
	}
}
