//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.4.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace JwtSecurity.HelperClasses
{
	/// <summary>Field Creation Class for entity ApiClientEntity</summary>
	public partial class ApiClientFields
	{
		/// <summary>Creates a new ApiClientEntity.ClientId field instance</summary>
		public static EntityField2 ClientId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ApiClientFieldIndex.ClientId); }}
		/// <summary>Creates a new ApiClientEntity.ClientName field instance</summary>
		public static EntityField2 ClientName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ApiClientFieldIndex.ClientName); }}
		/// <summary>Creates a new ApiClientEntity.ClientSecret field instance</summary>
		public static EntityField2 ClientSecret { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ApiClientFieldIndex.ClientSecret); }}
		/// <summary>Creates a new ApiClientEntity.RefreshTokenLifetimeMinutes field instance</summary>
		public static EntityField2 RefreshTokenLifetimeMinutes { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ApiClientFieldIndex.RefreshTokenLifetimeMinutes); }}
		/// <summary>Creates a new ApiClientEntity.TokenLifetimeMinutes field instance</summary>
		public static EntityField2 TokenLifetimeMinutes { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ApiClientFieldIndex.TokenLifetimeMinutes); }}
	}

	/// <summary>Field Creation Class for entity RoleEntity</summary>
	public partial class RoleFields
	{
		/// <summary>Creates a new RoleEntity.RoleId field instance</summary>
		public static EntityField2 RoleId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RoleFieldIndex.RoleId); }}
		/// <summary>Creates a new RoleEntity.RoleName field instance</summary>
		public static EntityField2 RoleName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RoleFieldIndex.RoleName); }}
	}

	/// <summary>Field Creation Class for entity UserEntity</summary>
	public partial class UserFields
	{
		/// <summary>Creates a new UserEntity.PasswordHash field instance</summary>
		public static EntityField2 PasswordHash { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.PasswordHash); }}
		/// <summary>Creates a new UserEntity.Salt field instance</summary>
		public static EntityField2 Salt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Salt); }}
		/// <summary>Creates a new UserEntity.UserEmail field instance</summary>
		public static EntityField2 UserEmail { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.UserEmail); }}
		/// <summary>Creates a new UserEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.UserId); }}
	}

	/// <summary>Field Creation Class for entity UserRoleEntity</summary>
	public partial class UserRoleFields
	{
		/// <summary>Creates a new UserRoleEntity.RoleId field instance</summary>
		public static EntityField2 RoleId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserRoleFieldIndex.RoleId); }}
		/// <summary>Creates a new UserRoleEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserRoleFieldIndex.UserId); }}
		/// <summary>Creates a new UserRoleEntity.UserRoleId field instance</summary>
		public static EntityField2 UserRoleId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserRoleFieldIndex.UserRoleId); }}
	}
	

}