//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.4.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using JwtSecurity.FactoryClasses;
using JwtSecurity.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace JwtSecurity.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitApiClientEntityInfo();
			InitRoleEntityInfo();
			InitUserEntityInfo();
			InitUserRoleEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits ApiClientEntity's info objects</summary>
		private void InitApiClientEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(ApiClientFieldIndex), "ApiClientEntity");
			this.AddElementFieldInfo("ApiClientEntity", "ClientId", typeof(System.String), true, false, false, false,  (int)ApiClientFieldIndex.ClientId, 50, 0, 0);
			this.AddElementFieldInfo("ApiClientEntity", "ClientName", typeof(System.String), false, false, false, false,  (int)ApiClientFieldIndex.ClientName, 50, 0, 0);
			this.AddElementFieldInfo("ApiClientEntity", "ClientSecret", typeof(System.String), false, false, false, false,  (int)ApiClientFieldIndex.ClientSecret, 50, 0, 0);
			this.AddElementFieldInfo("ApiClientEntity", "RefreshTokenLifetimeMinutes", typeof(System.Int32), false, false, false, false,  (int)ApiClientFieldIndex.RefreshTokenLifetimeMinutes, 0, 0, 10);
			this.AddElementFieldInfo("ApiClientEntity", "TokenLifetimeMinutes", typeof(System.Int32), false, false, false, false,  (int)ApiClientFieldIndex.TokenLifetimeMinutes, 0, 0, 10);
		}

		/// <summary>Inits RoleEntity's info objects</summary>
		private void InitRoleEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(RoleFieldIndex), "RoleEntity");
			this.AddElementFieldInfo("RoleEntity", "RoleId", typeof(System.Int32), true, false, false, false,  (int)RoleFieldIndex.RoleId, 0, 0, 10);
			this.AddElementFieldInfo("RoleEntity", "RoleName", typeof(System.String), false, false, false, false,  (int)RoleFieldIndex.RoleName, 255, 0, 0);
		}

		/// <summary>Inits UserEntity's info objects</summary>
		private void InitUserEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(UserFieldIndex), "UserEntity");
			this.AddElementFieldInfo("UserEntity", "PasswordHash", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.PasswordHash, 255, 0, 0);
			this.AddElementFieldInfo("UserEntity", "Salt", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.Salt, 255, 0, 0);
			this.AddElementFieldInfo("UserEntity", "UserEmail", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.UserEmail, 255, 0, 0);
			this.AddElementFieldInfo("UserEntity", "UserId", typeof(System.Int32), true, false, false, false,  (int)UserFieldIndex.UserId, 0, 0, 10);
		}

		/// <summary>Inits UserRoleEntity's info objects</summary>
		private void InitUserRoleEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(UserRoleFieldIndex), "UserRoleEntity");
			this.AddElementFieldInfo("UserRoleEntity", "RoleId", typeof(System.Int32), false, true, false, false,  (int)UserRoleFieldIndex.RoleId, 0, 0, 10);
			this.AddElementFieldInfo("UserRoleEntity", "UserId", typeof(System.Int32), false, true, false, false,  (int)UserRoleFieldIndex.UserId, 0, 0, 10);
			this.AddElementFieldInfo("UserRoleEntity", "UserRoleId", typeof(System.Int32), true, false, false, false,  (int)UserRoleFieldIndex.UserRoleId, 0, 0, 10);
		}
	}
}